### PR TITLE
[E2B-76] - Add test for compliance with the agent protocol

### PR DESCRIPTION
**Pull request by jakubno**
The test can be triggered by running 

```shell
agent-protocol
```

Should I make it more future proof with something like?
```shell
agent-protocol --test
```

### CODE REVIEW

**Comment by mlejva** [comment]
Nice! This looks great.

**Comment by mlejva** [comment]
I'm sorry, I missed your question @jakubno  🤦.

> Should I make it more future proof with something like?
> `agent-protocol --test`

I think that would be a good idea. I would also add a flag or an argument that would allow users to specify the whole URL with port where the agent runs. Maybe something like

```
agent-protocol validate http://localhost:8000
```

What do you think?

**Comment by mlejva** [comment]
Thinking about it. Maybe we should make it installable as a separate CLI. From my understanding of this PR, one would need to clone the repo and run the `agent-protocol` inside the python dir. Am I understanding it correctly?

**Comment by jakubno** [comment]
No, I made it part of `agent-protocol` package, if you install `agent-protocol`. If you have active virtual environment, you should be able run the command in shell, no need to clone repo.

I thought about creating it as standalone package, but because this reasons I decided to add it as a part of `agent-protocol` package:
- I wanted to use the models to check the output and didn't want to duplicate the code
- There will be significant part of the users using `agent-protocol` package, so they don't have to install another package

But I am open to change it to standalone package if you think it'll be better that way

**Comment by mlejva** [comment]
Got it. I think as long as people can just install the package then we're good. The only challenge for users might be having an active virtual env. We'll see if that's an obstacle.
So to summarize this - I think we're good. People can just do `pip install agent-protocol` and it'll work.

Do you think we can add the same functionality to the NPM package?

**Comment by jzanecook** [comment]
> Do you think we can add the same functionality to the NPM package?

Yes.

**Pull request merged**
