### PR TITLE
Make CLI for testing the compliance with agent protocol

### PR DESCRIPTION
**Pull request by jakubno**
- I added an argument for url 
- Moved everything under test command
- Cleaned up few things

### CODE REVIEW

**Comment by mlejva** [comment]
Nice! I think the last thing we're missing is just the mention on how to use the CLI in the readme

**Comment by mlejva** [comment]
I think we can merge this @jakubno if there's nothing more on your end. What do you think?

**Comment by mlejva** [comment]
Thinking about it a bit more - maybe we should mention the CLI in the main readme as well. This is something even JS/TS users will want to use. That's why I'm a bit worried that requiring from users to set up poetry and virtual python env will be pain. Folks from JS/TS world don't know this.

**Comment by jzanecook** [comment]
> Folks from JS/TS world don't know this.

Could there be a way to replicate it natively to JS/TS? Like an npx tool? If I'm not mistaken, it could even be just a wrapper for the python client with a script that sets everything up.

**Comment by jakubno** [comment]
Sure, I will mention it there as well.

>That's why I'm a bit worried that requiring from users to set up poetry and virtual python env will be pain. Folks from JS/TS world don't know this.
I will rewrite the docs, probably it isn't clear. You only need to run
```sh
pip install agent-protocol
```
then you can run 
```sh
agent-protocol test -u localhost:8000
```

`python` and therefore `pip` are by default on Mac / Linux, the only problem could be Windows without `python` installed.

But we can add the same functionality to the JS package as well, it should be quite easy

**Comment by mlejva** [comment]
I think this is good DX. Ultimately I don't think it matters if you need to run `pip install` or `npm i` (we might want to have `brew` installation in the future). The point is that you can now just run `agent-protocol` and it'll work without anything else.

Merging and closing. Thanks!

**Pull request merged**
